/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Nesh
 */
public class BookDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form BookDetailDialog
     */
    public BookDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoThumbnailImage = new javax.swing.JPanel();
        infoThumb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        BTNbarcode = new javax.swing.JButton();
        BTNqrcode = new javax.swing.JButton();
        BTNprint = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        BTNdelete.setVisible(false);
        BTNrenew = new javax.swing.JButton();
        BTNcheckItem = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        infoTitle = new javax.swing.JTextField();
        infoLanguage = new javax.swing.JTextField();
        infoPageCount = new javax.swing.JTextField();
        infoGenre = new javax.swing.JTextField();
        infoISBN10 = new javax.swing.JTextField();
        infoISBN13 = new javax.swing.JTextField();
        infoPublisher = new javax.swing.JTextField();
        infoSponsor = new javax.swing.JTextField();
        infoBuyedDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoNotes = new javax.swing.JTextArea();
        BTNaddAuthor = new javax.swing.JButton();
        BTNaddAuthor.setVisible(false);
        jScrollPane3 = new javax.swing.JScrollPane();
        infoAuthors = new javax.swing.JList();
        BTNremoveAuthors = new javax.swing.JButton();
        BTNremoveAuthors.setVisible(false);
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        BTNsetPublishedYear = new javax.swing.JButton();
        BTNsetPublishedYear.setVisible(false);
        infoPublishedYear = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lastBorrowTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        infoStock = new javax.swing.JLabel();
        INPselectTargetBook = new javax.swing.JComboBox();
        infoLocation = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informace o knize");
        setMaximumSize(new java.awt.Dimension(1080, 650));
        setMinimumSize(new java.awt.Dimension(840, 650));
        setPreferredSize(new java.awt.Dimension(840, 650));
        setResizable(false);

        infoThumbnailImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Náhled"));
        infoThumbnailImage.setToolTipText("Náhledy nemusí vždy odpovídat skutečnosti");
        infoThumbnailImage.setMaximumSize(new java.awt.Dimension(205, 297));
        infoThumbnailImage.setMinimumSize(new java.awt.Dimension(205, 297));

        infoThumb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoThumb.setText("Hledám náhled...");

        javax.swing.GroupLayout infoThumbnailImageLayout = new javax.swing.GroupLayout(infoThumbnailImage);
        infoThumbnailImage.setLayout(infoThumbnailImageLayout);
        infoThumbnailImageLayout.setHorizontalGroup(
            infoThumbnailImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoThumbnailImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoThumbnailImageLayout.setVerticalGroup(
            infoThumbnailImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoThumbnailImageLayout.createSequentialGroup()
                .addComponent(infoThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informace o knize"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Autoři:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Jazyk:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Titul:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Vydavatel:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Poznámky:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Rok vydání:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ISBN10:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ISBN13:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Počet str:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Žánr:");

        editButton.setText("Upravit");
        editButton.setToolTipText("Upravit knihu");
        editButton.setName("editButton"); // NOI18N

        closeButton.setText("Zavřít");
        closeButton.setToolTipText("Zavře dialog");
        closeButton.setName("closeButton"); // NOI18N

        BTNbarcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PDF417-Java-Barcode.icon.gif"))); // NOI18N
        BTNbarcode.setToolTipText("Čárový kód");
        BTNbarcode.setName("barcode"); // NOI18N

        BTNqrcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr-icon.png"))); // NOI18N
        BTNqrcode.setToolTipText("QR kód");
        BTNqrcode.setName("qrcode"); // NOI18N

        BTNprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print-icon.png"))); // NOI18N
        BTNprint.setToolTipText("Tisknout detail knihy");
        BTNprint.setName("printPDF"); // NOI18N

        BTNdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-can-delete.png"))); // NOI18N
        BTNdelete.setToolTipText("Smazat položku");
        BTNdelete.setName("delete"); // NOI18N

        BTNrenew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-2-icon.png"))); // NOI18N
        BTNrenew.setToolTipText("Obnovit položku");
        BTNrenew.setName("renew"); // NOI18N

        BTNcheckItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-icon.png"))); // NOI18N
        BTNcheckItem.setToolTipText("Inventura");
        BTNcheckItem.setName("checkItem"); // NOI18N
        BTNcheckItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcheckItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNqrcode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNrenew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNdelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BTNbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNcheckItem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addGap(45, 45, 45)
                .addComponent(BTNprint, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNqrcode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNbarcode, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNcheckItem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNdelete)
                    .addComponent(BTNrenew))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Sponzor:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Zakoupeno dne:");

        infoTitle.setEditable(false);
        infoTitle.setToolTipText("");
        infoTitle.setMaximumSize(new java.awt.Dimension(312, 14));
        infoTitle.setMinimumSize(new java.awt.Dimension(312, 14));
        infoTitle.setPreferredSize(new java.awt.Dimension(312, 20));

        infoLanguage.setEditable(false);
        infoLanguage.setMaximumSize(new java.awt.Dimension(312, 14));
        infoLanguage.setMinimumSize(new java.awt.Dimension(312, 14));
        infoLanguage.setPreferredSize(new java.awt.Dimension(312, 20));

        infoPageCount.setEditable(false);
        infoPageCount.setMaximumSize(new java.awt.Dimension(312, 14));
        infoPageCount.setMinimumSize(new java.awt.Dimension(312, 14));
        infoPageCount.setPreferredSize(new java.awt.Dimension(312, 20));

        infoGenre.setEditable(false);
        infoGenre.setMaximumSize(new java.awt.Dimension(312, 14));
        infoGenre.setMinimumSize(new java.awt.Dimension(312, 14));
        infoGenre.setName("genres"); // NOI18N
        infoGenre.setPreferredSize(new java.awt.Dimension(312, 20));

        infoISBN10.setEditable(false);
        infoISBN10.setMaximumSize(new java.awt.Dimension(312, 14));
        infoISBN10.setMinimumSize(new java.awt.Dimension(312, 14));
        infoISBN10.setPreferredSize(new java.awt.Dimension(312, 20));

        infoISBN13.setEditable(false);
        infoISBN13.setMaximumSize(new java.awt.Dimension(312, 14));
        infoISBN13.setMinimumSize(new java.awt.Dimension(312, 14));
        infoISBN13.setPreferredSize(new java.awt.Dimension(312, 20));

        infoPublisher.setEditable(false);
        infoPublisher.setMaximumSize(new java.awt.Dimension(312, 14));
        infoPublisher.setMinimumSize(new java.awt.Dimension(312, 14));
        infoPublisher.setPreferredSize(new java.awt.Dimension(312, 20));

        infoSponsor.setEditable(false);
        infoSponsor.setMaximumSize(new java.awt.Dimension(312, 14));
        infoSponsor.setMinimumSize(new java.awt.Dimension(312, 14));
        infoSponsor.setPreferredSize(new java.awt.Dimension(312, 20));

        infoBuyedDate.setEditable(false);
        infoBuyedDate.setMaximumSize(new java.awt.Dimension(312, 14));
        infoBuyedDate.setMinimumSize(new java.awt.Dimension(312, 14));
        infoBuyedDate.setPreferredSize(new java.awt.Dimension(312, 20));

        infoNotes.setEditable(false);
        infoNotes.setBackground(new java.awt.Color(240, 240, 240));
        infoNotes.setColumns(20);
        infoNotes.setRows(5);
        jScrollPane2.setViewportView(infoNotes);

        BTNaddAuthor.setText("+");
        BTNaddAuthor.setName("addAuthor"); // NOI18N

        infoAuthors.setBackground(new java.awt.Color(240, 240, 240));
        infoAuthors.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(infoAuthors);

        BTNremoveAuthors.setText("-");
        BTNremoveAuthors.setName("removeAuthors"); // NOI18N

        BTNsetPublishedYear.setText("...");
        BTNsetPublishedYear.setName("publishedYear"); // NOI18N

        infoPublishedYear.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(infoSponsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoISBN10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoISBN13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(infoPageCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTNaddAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTNremoveAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(infoBuyedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNsetPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BTNaddAuthor)
                                .addGap(18, 18, 18)
                                .addComponent(BTNremoveAuthors))
                            .addComponent(jLabel6)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(infoLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(infoPageCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(infoGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoISBN10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infoISBN13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(infoPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(infoPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoSponsor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNsetPublishedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(infoBuyedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Poslední vypůjčení této knihy"));

        lastBorrowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(lastBorrowTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sklad"));

        infoStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        infoStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoStock.setText("1/2");

        INPselectTargetBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        INPselectTargetBook.setName("selectItem"); // NOI18N
        INPselectTargetBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPselectTargetBookActionPerformed(evt);
            }
        });

        infoLocation.setEditable(false);
        infoLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        infoLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoLocation.setText("R2D");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPselectTargetBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoLocation))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(infoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(INPselectTargetBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoThumbnailImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoThumbnailImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INPselectTargetBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPselectTargetBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPselectTargetBookActionPerformed

    private void BTNcheckItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcheckItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNcheckItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNaddAuthor;
    private javax.swing.JButton BTNbarcode;
    private javax.swing.JButton BTNcheckItem;
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNprint;
    private javax.swing.JButton BTNqrcode;
    private javax.swing.JButton BTNremoveAuthors;
    private javax.swing.JButton BTNrenew;
    private javax.swing.JButton BTNsetPublishedYear;
    private javax.swing.JComboBox INPselectTargetBook;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton editButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JList infoAuthors;
    private javax.swing.JTextField infoBuyedDate;
    private javax.swing.JTextField infoGenre;
    private javax.swing.JTextField infoISBN10;
    private javax.swing.JTextField infoISBN13;
    private javax.swing.JTextField infoLanguage;
    private javax.swing.JTextField infoLocation;
    private javax.swing.JTextArea infoNotes;
    private javax.swing.JTextField infoPageCount;
    private javax.swing.JTextField infoPublishedYear;
    private javax.swing.JTextField infoPublisher;
    private javax.swing.JTextField infoSponsor;
    private javax.swing.JLabel infoStock;
    private javax.swing.JLabel infoThumb;
    private javax.swing.JPanel infoThumbnailImage;
    private javax.swing.JTextField infoTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lastBorrowTable;
    // End of variables declaration//GEN-END:variables

    public JButton getCloseButton() {
        return closeButton;
    }

    public JButton getEditButton() {
        return editButton;
    }

    public JList getInfoAuthors() {
        return infoAuthors;
    }

    public JTextField getInfoBuyedDate() {
        return infoBuyedDate;
    }

    public JTextField getInfoGenre() {
        return infoGenre;
    }

    public JTextField getInfoISBN10() {
        return infoISBN10;
    }

    public JTextField getInfoISBN13() {
        return infoISBN13;
    }

    public JTextField getInfoLanguage() {
        return infoLanguage;
    }

    public JTextField getInfoLocation() {
        return infoLocation;
    }

    public JTextArea getInfoNotes() {
        return infoNotes;
    }

    public JTextField getInfoPageCount() {
        return infoPageCount;
    }

    public JTextField getInfoPublishedYear() {
        return infoPublishedYear;
    }

    public JTextField getInfoPublisher() {
        return infoPublisher;
    }

    public JTextField getInfoSponsor() {
        return infoSponsor;
    }

    public JLabel getInfoStock() {
        return infoStock;
    }

    public JTextField getInfoTitle() {
        return infoTitle;
    }

    public JLabel getInfoThumb() {
        return infoThumb;
    }

    public JPanel getInfoThumbnailImage() {
        return infoThumbnailImage;
    }

    public JTable getLastBorrowTable() {
        return lastBorrowTable;
    }

    public JButton getBTNdelete() {
        return BTNdelete;
    }

    public JComboBox getINPselectTargetBook() {
        return INPselectTargetBook;
    }

    public JButton getBTNaddAuthor() {
        return BTNaddAuthor;
    }

    public JButton getBTNremoveAuthors() {
        return BTNremoveAuthors;
    }

    public JButton getBTNsetPublishedYear() {
        return BTNsetPublishedYear;
    }

    public JButton getBTNbarcode() {
        return BTNbarcode;
    }

    public JButton getBTNqrcode() {
        return BTNqrcode;
    }

    public JButton getBTNprint() {
        return BTNprint;
    }

    public JButton getBTNcheckItem() {
        return BTNcheckItem;
    }

    public JButton getBTNrenew() {
        return BTNrenew;
    }
}