/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Nesh
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainView() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/LSIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jSeparator5 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        newItemButton = new javax.swing.JButton();
        newBorrowButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        newCustomerButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BTNsearch = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        barcodeButton = new javax.swing.JButton();
        qrcodeButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        connectionButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        systemUserLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        TabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bookFilterInput = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        bookTableNextButton = new javax.swing.JButton();
        bookTablePrevButton = new javax.swing.JButton();
        bookTableTotalPage = new javax.swing.JLabel();
        bookTableInputNumber = new javax.swing.JTextField();
        BTNstopBookSearch = new javax.swing.JButton();
        BTNstopBookSearch.setVisible(false);
        jPanel4 = new javax.swing.JPanel();
        customerFilterButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customerTablePrevButton = new javax.swing.JButton();
        customerTableInputNumber = new javax.swing.JTextField();
        customerTableTotalPage = new javax.swing.JLabel();
        customerTableNextButton = new javax.swing.JButton();
        customerFilterInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BTNstopCustomerSearch = new javax.swing.JButton();
        BTNstopCustomerSearch.setVisible(false);
        jPanel2 = new javax.swing.JPanel();
        borrowFilterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        INPborrowFilter = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        borrowTable = new javax.swing.JTable();
        borrowPrevButton = new javax.swing.JButton();
        INPborrowPageNumber = new javax.swing.JTextField();
        borrowTotalPageNumber = new javax.swing.JLabel();
        borrowNextButton = new javax.swing.JButton();
        BTNstopBorrowSearch = new javax.swing.JButton();
        BTNstopBorrowSearch.setVisible(false);
        jPanel3 = new javax.swing.JPanel();
        BTNnotificationFilter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        INPnotificationFilter = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TABnotification = new javax.swing.JTable();
        BTNnotificationPrev = new javax.swing.JButton();
        INPnotificationPage = new javax.swing.JTextField();
        INPnotificationTotalPage = new javax.swing.JLabel();
        BTNnotificationNext = new javax.swing.JButton();
        BTNnotificationStopSearch = new javax.swing.JButton();
        BTNnotificationStopSearch.setVisible(false);
        jScrollPane2 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LibSys - Knihovní systém");
        setMinimumSize(new java.awt.Dimension(965, 748));

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        newItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_add2.gif"))); // NOI18N
        newItemButton.setToolTipText("Přidat novou položku");
        newItemButton.setFocusable(false);
        newItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newItemButton.setName("newItem"); // NOI18N
        newItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newItemButton);

        newBorrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrow-icon.png"))); // NOI18N
        newBorrowButton.setToolTipText("Vytvoření nové půjčky");
        newBorrowButton.setFocusable(false);
        newBorrowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newBorrowButton.setName("newBorrow"); // NOI18N
        newBorrowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newBorrowButton);
        jToolBar1.add(jSeparator1);

        newCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.gif"))); // NOI18N
        newCustomerButton.setFocusable(false);
        newCustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newCustomerButton.setName("newCustomerButton"); // NOI18N
        newCustomerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newCustomerButton);
        jToolBar1.add(jSeparator2);

        BTNsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        BTNsearch.setFocusable(false);
        BTNsearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNsearch.setName("searchDialog"); // NOI18N
        BTNsearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BTNsearch);
        jToolBar1.add(jSeparator6);

        barcodeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode-icon.png"))); // NOI18N
        barcodeButton.setFocusable(false);
        barcodeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barcodeButton.setName("barcode"); // NOI18N
        barcodeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(barcodeButton);

        qrcodeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr-icon.png"))); // NOI18N
        qrcodeButton.setFocusable(false);
        qrcodeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qrcodeButton.setName("qrcode"); // NOI18N
        qrcodeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(qrcodeButton);
        jToolBar1.add(jSeparator4);

        connectionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        connectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/server-icon.png"))); // NOI18N
        connectionButton.setText("LibSys Server");
        connectionButton.setToolTipText("LibSys Server");
        connectionButton.setFocusable(false);
        connectionButton.setIconTextGap(5);
        connectionButton.setName("connection"); // NOI18N
        jToolBar1.add(connectionButton);
        jToolBar1.add(filler2);

        systemUserLabel.setForeground(new java.awt.Color(0, 153, 0));
        systemUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        systemUserLabel.setMaximumSize(new java.awt.Dimension(150, 14));
        systemUserLabel.setMinimumSize(new java.awt.Dimension(150, 14));
        systemUserLabel.setPreferredSize(new java.awt.Dimension(150, 14));
        jToolBar1.add(systemUserLabel);
        jToolBar1.add(filler3);

        TabPanel.setName(""); // NOI18N

        jPanel1.setName("bookTab"); // NOI18N

        catalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        catalogTable.setName("bookTable"); // NOI18N
        jScrollPane1.setViewportView(catalogTable);

        jLabel1.setText("Rychlý filtr:");

        bookFilterInput.setName("bookFilter"); // NOI18N

        filterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        filterButton.setText("Volby zobrazení");
        filterButton.setToolTipText("upravit způsob zobrazení");
        filterButton.setMaximumSize(new java.awt.Dimension(107, 30));
        filterButton.setMinimumSize(new java.awt.Dimension(107, 30));
        filterButton.setName("filter"); // NOI18N
        filterButton.setPreferredSize(new java.awt.Dimension(107, 30));

        bookTableNextButton.setText(">");
        bookTableNextButton.setName("nextPage"); // NOI18N

        bookTablePrevButton.setText("<");
        bookTablePrevButton.setName("prevPage"); // NOI18N

        bookTableTotalPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bookTableTotalPage.setText("/ 5");

        bookTableInputNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bookTableInputNumber.setText("1");
        bookTableInputNumber.setName("bookPageNumber"); // NOI18N

        BTNstopBookSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        BTNstopBookSearch.setText("Zrušit hledání");
        BTNstopBookSearch.setToolTipText("Přeruší vyhledávání");
        BTNstopBookSearch.setMaximumSize(new java.awt.Dimension(121, 30));
        BTNstopBookSearch.setMinimumSize(new java.awt.Dimension(121, 30));
        BTNstopBookSearch.setName("stopSearch"); // NOI18N
        BTNstopBookSearch.setPreferredSize(new java.awt.Dimension(121, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookTablePrevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookTableInputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookTableTotalPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookTableNextButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNstopBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNstopBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTableNextButton)
                    .addComponent(bookTablePrevButton)
                    .addComponent(bookTableTotalPage)
                    .addComponent(bookTableInputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        TabPanel.addTab("Knihovna", jPanel1);

        jPanel4.setName("customerTab"); // NOI18N

        customerFilterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        customerFilterButton.setText("Volby zobrazení");
        customerFilterButton.setMaximumSize(new java.awt.Dimension(107, 30));
        customerFilterButton.setMinimumSize(new java.awt.Dimension(107, 30));
        customerFilterButton.setName("filter"); // NOI18N
        customerFilterButton.setPreferredSize(new java.awt.Dimension(107, 30));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        customerTable.setName("customerTable"); // NOI18N
        jScrollPane5.setViewportView(customerTable);

        customerTablePrevButton.setText("<");
        customerTablePrevButton.setName("prevPage"); // NOI18N

        customerTableInputNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        customerTableInputNumber.setText("1");
        customerTableInputNumber.setName("bookPageNumber"); // NOI18N

        customerTableTotalPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerTableTotalPage.setText("/ 5");

        customerTableNextButton.setText(">");
        customerTableNextButton.setName("nextPage"); // NOI18N

        customerFilterInput.setName("customerFilter"); // NOI18N

        jLabel2.setText("Rychlý filtr:");

        BTNstopCustomerSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        BTNstopCustomerSearch.setText("Zrušit hledání");
        BTNstopCustomerSearch.setToolTipText("Přeruší vyhledávání");
        BTNstopCustomerSearch.setMaximumSize(new java.awt.Dimension(121, 30));
        BTNstopCustomerSearch.setMinimumSize(new java.awt.Dimension(121, 30));
        BTNstopCustomerSearch.setName("stopSearch"); // NOI18N
        BTNstopCustomerSearch.setPreferredSize(new java.awt.Dimension(121, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(customerTablePrevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTableInputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTableTotalPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTableNextButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(customerFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNstopCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNstopCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerFilterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerTableNextButton)
                    .addComponent(customerTablePrevButton)
                    .addComponent(customerTableTotalPage)
                    .addComponent(customerTableInputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        TabPanel.addTab("Zákazníci", jPanel4);

        jPanel2.setName("borrowTab"); // NOI18N

        borrowFilterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        borrowFilterButton.setText("Volby zobrazení");
        borrowFilterButton.setName("filter"); // NOI18N

        jLabel3.setText("Rychlý filtr:");

        INPborrowFilter.setName("borrowFilter"); // NOI18N

        borrowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        borrowTable.setName("borrowTable"); // NOI18N
        jScrollPane3.setViewportView(borrowTable);

        borrowPrevButton.setText("<");
        borrowPrevButton.setName("prevPage"); // NOI18N

        INPborrowPageNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        INPborrowPageNumber.setText("1");
        INPborrowPageNumber.setName("borrowPageNumber"); // NOI18N

        borrowTotalPageNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        borrowTotalPageNumber.setText("/ 5");

        borrowNextButton.setText(">");
        borrowNextButton.setName("nextPage"); // NOI18N

        BTNstopBorrowSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        BTNstopBorrowSearch.setText("Zrušit hledání");
        BTNstopBorrowSearch.setToolTipText("Přeruší vyhledávání");
        BTNstopBorrowSearch.setFocusable(false);
        BTNstopBorrowSearch.setMaximumSize(new java.awt.Dimension(121, 30));
        BTNstopBorrowSearch.setMinimumSize(new java.awt.Dimension(121, 30));
        BTNstopBorrowSearch.setName("stopSearch"); // NOI18N
        BTNstopBorrowSearch.setPreferredSize(new java.awt.Dimension(121, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(borrowPrevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPborrowPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowTotalPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrowNextButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(borrowFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNstopBorrowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPborrowFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNstopBorrowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPborrowFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowNextButton)
                    .addComponent(borrowPrevButton)
                    .addComponent(borrowTotalPageNumber)
                    .addComponent(INPborrowPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        TabPanel.addTab("Půjčky", jPanel2);

        jPanel3.setName("notificationTab"); // NOI18N

        BTNnotificationFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-icon.png"))); // NOI18N
        BTNnotificationFilter.setText("Volby zobrazení");
        BTNnotificationFilter.setName("filter"); // NOI18N

        jLabel5.setText("Rychlý filtr:");

        INPnotificationFilter.setName("filter"); // NOI18N

        TABnotification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TABnotification.setName("notificationTable"); // NOI18N
        jScrollPane4.setViewportView(TABnotification);

        BTNnotificationPrev.setText("<");
        BTNnotificationPrev.setName("prevPage"); // NOI18N

        INPnotificationPage.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        INPnotificationPage.setText("1");
        INPnotificationPage.setName("page"); // NOI18N

        INPnotificationTotalPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        INPnotificationTotalPage.setText("/ 5");

        BTNnotificationNext.setText(">");
        BTNnotificationNext.setName("nextPage"); // NOI18N

        BTNnotificationStopSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_icon.png"))); // NOI18N
        BTNnotificationStopSearch.setText("Zrušit hledání");
        BTNnotificationStopSearch.setName("stop"); // NOI18N
        BTNnotificationStopSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnotificationStopSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNnotificationPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPnotificationPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPnotificationTotalPage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNnotificationNext))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNnotificationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(BTNnotificationStopSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPnotificationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNnotificationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNnotificationStopSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPnotificationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNnotificationNext)
                    .addComponent(BTNnotificationPrev)
                    .addComponent(INPnotificationTotalPage)
                    .addComponent(INPnotificationPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        TabPanel.addTab("Oznámení (5)", jPanel3);

        console.setEditable(false);
        console.setColumns(20);
        console.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        console.setRows(5);
        console.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        console.setMaximumSize(new java.awt.Dimension(162, 67));
        console.setMinimumSize(new java.awt.Dimension(162, 67));
        jScrollPane2.setViewportView(console);

        jMenu1.setText("LibSys");

        logoutMenuItem.setText("Odhlásit se");
        logoutMenuItem.setName("logout"); // NOI18N
        jMenu1.add(logoutMenuItem);

        exitMenuItem.setText("Konec");
        exitMenuItem.setName("exit"); // NOI18N
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Nástroje");

        settingsMenuItem.setText("Nastavení");
        settingsMenuItem.setName("settings"); // NOI18N
        jMenu4.add(settingsMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Nápověda");

        helpMenuItem.setText("Nápověda");
        helpMenuItem.setName("help"); // NOI18N
        jMenu2.add(helpMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(TabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TabPanel.getAccessibleContext().setAccessibleName("Knihovna");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BTNnotificationStopSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnotificationStopSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNnotificationStopSearchActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNnotificationFilter;
    private javax.swing.JButton BTNnotificationNext;
    private javax.swing.JButton BTNnotificationPrev;
    private javax.swing.JButton BTNnotificationStopSearch;
    private javax.swing.JButton BTNsearch;
    private javax.swing.JButton BTNstopBookSearch;
    private javax.swing.JButton BTNstopBorrowSearch;
    private javax.swing.JButton BTNstopCustomerSearch;
    private javax.swing.JTextField INPborrowFilter;
    private javax.swing.JTextField INPborrowPageNumber;
    private javax.swing.JTextField INPnotificationFilter;
    private javax.swing.JTextField INPnotificationPage;
    private javax.swing.JLabel INPnotificationTotalPage;
    private javax.swing.JTable TABnotification;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JButton barcodeButton;
    private javax.swing.JTextField bookFilterInput;
    private javax.swing.JTextField bookTableInputNumber;
    private javax.swing.JButton bookTableNextButton;
    private javax.swing.JButton bookTablePrevButton;
    private javax.swing.JLabel bookTableTotalPage;
    private javax.swing.JButton borrowFilterButton;
    private javax.swing.JButton borrowNextButton;
    private javax.swing.JButton borrowPrevButton;
    private javax.swing.JTable borrowTable;
    private javax.swing.JLabel borrowTotalPageNumber;
    private javax.swing.JTable catalogTable;
    private javax.swing.JButton connectionButton;
    private javax.swing.JTextArea console;
    private javax.swing.JButton customerFilterButton;
    private javax.swing.JTextField customerFilterInput;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField customerTableInputNumber;
    private javax.swing.JButton customerTableNextButton;
    private javax.swing.JButton customerTablePrevButton;
    private javax.swing.JLabel customerTableTotalPage;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton filterButton;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JButton newBorrowButton;
    private javax.swing.JButton newCustomerButton;
    private javax.swing.JButton newItemButton;
    private javax.swing.JButton qrcodeButton;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JLabel systemUserLabel;
    // End of variables declaration//GEN-END:variables

    /*
     * BASIC
     */
    public JLabel getSystemUserLabel() {
        return systemUserLabel;
    }

    public JTextArea getConsole() {
        return console;
    }

    public JTabbedPane getTabPanel() {
        return TabPanel;
    }

    /*
     * MENU ITEMS
     */
    public JButton getQrcodeButton() {
        return qrcodeButton;
    }

    public JButton getConnectionButton() {
        return connectionButton;
    }

    public JButton getNewItemButton() {
        return newItemButton;
    }

    public JButton getBTNsearch() {
        return BTNsearch;
    }

    public JButton getNewBorrowButton() {
        return newBorrowButton;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenuItem getLogoutMenuItem() {
        return logoutMenuItem;
    }

    public JButton getNewCustomerButton() {
        return newCustomerButton;
    }

    public JButton getBarcodeButton() {
        return barcodeButton;
    }

    public JMenuItem getSettingsMenuItem() {
        return settingsMenuItem;
    }

    public JMenuItem getHelpMenuItem() {
        return helpMenuItem;
    }

    /*
     * CATALOG TAB
     */
    public JTable getCatalogTable() {
        return catalogTable;
    }

    public JButton getFilterButton() {
        return filterButton;
    }

    public JTextField getBookTableInputNumber() {
        return bookTableInputNumber;
    }

    public JButton getBookTableNextButton() {
        return bookTableNextButton;
    }

    public JButton getBookTablePrevButton() {
        return bookTablePrevButton;
    }

    public JLabel getBookTableTotalPage() {
        return bookTableTotalPage;
    }

    /*
     * BORROW TAB 
     */
    public JTable getBorrowTable() {
        return borrowTable;
    }

    public JTextField getBorrowInputPageNumber() {
        return INPborrowPageNumber;
    }

    public JButton getBorrowNextButton() {
        return borrowNextButton;
    }

    public JButton getBorrowPrevButton() {
        return borrowPrevButton;
    }

    public JLabel getBorrowTotalPageNumber() {
        return borrowTotalPageNumber;
    }

    public JButton getBorrowFilterButton() {
        return borrowFilterButton;
    }

    public JTextField getBookFilterInput() {
        return bookFilterInput;
    }

    public JButton getBTNstopBorrowSearch() {
        return BTNstopBorrowSearch;
    }

    public JTextField getINPborrowFilter() {
        return INPborrowFilter;
    }

    public JTextField getINPborrowPageNumber() {
        return INPborrowPageNumber;
    }

    /*
     * CUSTOMER TAB
     */
    public JButton getCustomerFilterButton() {
        return customerFilterButton;
    }

    public JTextField getCustomerFilterInput() {
        return customerFilterInput;
    }

    public JTable getCustomerTable() {
        return customerTable;
    }

    public JTextField getCustomerTableInputNumber() {
        return customerTableInputNumber;
    }

    public JButton getCustomerTableNextButton() {
        return customerTableNextButton;
    }

    public JButton getCustomerTablePrevButton() {
        return customerTablePrevButton;
    }

    public JLabel getCustomerTableTotalPage() {
        return customerTableTotalPage;
    }

    public JButton getBTNstopBookSearch() {
        return BTNstopBookSearch;
    }

    public JButton getBTNstopCustomerSearch() {
        return BTNstopCustomerSearch;
    }

    public JTable getTABnotification() {
        return TABnotification;
    }

    /*
     * NOTIFICATION TAB
     */
    public JButton getBTNnotificationFilter() {
        return BTNnotificationFilter;
    }

    public JButton getBTNnotificationNext() {
        return BTNnotificationNext;
    }

    public JButton getBTNnotificationPrev() {
        return BTNnotificationPrev;
    }

    public JButton getBTNnotificationStopSearch() {
        return BTNnotificationStopSearch;
    }

    public JTextField getINPnotificationFilter() {
        return INPnotificationFilter;
    }

    public JTextField getINPnotificationPage() {
        return INPnotificationPage;
    }

    public JLabel getINPnotificationTotalPage() {
        return INPnotificationTotalPage;
    }
}
